#!/bin/bash

wlan=$1

clear

ifconfig $wlan down
iwconfig $wlan mode managed
ifconfig $wlan up

cp test_pattern.png /tmp/output.png
cp test_pattern.png /tmp/output1.png
cp test_pattern.png /tmp/output2.png

fbi -noverbose  -T 2 -t 1  --cachemem 0  --noedit   /tmp/output.png /tmp/output1.png /tmp/output2.png  >/dev/null 2>&1

function finish {
  rm /tmp/histogram.dat
  rm /tmp/output*.png

  pkill fbi
  
}
trap finish EXIT



while true
do
                touch /tmp/fft.dump.all
                echo chanscan \
                        | tee /sys/kernel/debug/ieee80211/phy*/ath9k_htc/spectral_scan_ctl \
                        >/dev/null
                iw $wlan scan    >/dev/null 2>&1

                cat /sys/kernel/debug/ieee80211/phy*/ath9k_htc/spectral_scan0 | ./ath9k-spectral-scan/fft2txt | awk '{print $4 " " $6}' > /tmp/fft.dump.all
                python hist2d.py > /dev/null 2>&1
                gnuplot hist2d.gpl > /dev/null 2>&1
		cp /tmp/output.png /tmp/output1.png
		cp /tmp/output.png /tmp/output2.png

done
